feat: micrio redesign
SlovakNationalGallery/sakra-stex pull request #1
Opened 2023-10-26 12:38 UTC by FrantisekMichalSebestyen

2023-10-27 11:43 UTC, eronisko requested changes
I'm happy that you've made it work, it seems to have been tricky. Thank you. Please tweak the component's API and the design details mentioned in my comments.

2023-10-27 11:43 UTC, eronisko commented on tailwind.config.js
> -      body: ["Inter", ...defaultTheme.fontFamily.sans],
If we're not using Inter anymore, we should remove it from the app as well. Look at nuxt.config.ts please

2023-10-27 11:43 UTC, eronisko commented on tailwind.config.js
> +    },
Please put this in the `micrio.css` file with the other animation (if it's being used).

2023-10-27 11:43 UTC, eronisko commented on components/Micrio.vue
> +    :currentStepIndex="currentStepIndex"
This API doesn't really make sense outside of this particular use-case. We're aiming for a re-usable component here which we can later deploy in other apps.

Could `currentStep` and `isPopoverHidden` be devised from `marker`?

Something like this would be nicer (but it might need some work to make sure it conveys everything it should convey):

```suggestion
    :marker="markerRef"
```

2023-10-27 11:43 UTC, eronisko commented on components/Micrio.vue
> +    const markersRef = document.querySelectorAll("button.micrio-marker");
This is no longer a ref (which is good)
```suggestion
    const markers = document.querySelectorAll("button.micrio-marker");
```

2023-10-27 11:43 UTC, eronisko commented on components/Micrio.vue
> +    class="h-full"
Styling should go outside of the component

```suggestion
```

2023-10-27 11:43 UTC, eronisko commented on components/Micrio.vue
> +        }
You already have this checked for falsey.
```suggestion
        const markerTour = tour as
          | Models.ImageCultureData.MarkerTour;

        tourSteps.value = markerTour.steps;
```

2023-10-27 11:43 UTC, eronisko commented on components/Micrio.vue
> +  }
Please check your Prettier config.

2023-10-27 11:43 UTC, eronisko commented on app.vue
> +                  <div v-html="micrio.markerRef.body" class="text-xl"/>
Please check if rich-text features (bold, italics, etc) still work.

2023-10-27 11:43 UTC, eronisko commented on assets/img/arrow-left.svg
It's not a good idea to include icons with padding IMHO. Please check this export.

2023-10-27 11:43 UTC, eronisko commented on assets/css/micrio.css
> +  @apply w-12 h-12 text-3xl flex items-center justify-center border-none !important;
This
<img width="98" alt="image" src="https://github.com/SlovakNationalGallery/sakra-stex/assets/1374745/80a394e5-20e0-44f6-b213-a4cb0c14e32c">

Figma
<img width="157" alt="image" src="https://github.com/SlovakNationalGallery/sakra-stex/assets/1374745/05d2b10e-e959-4837-ad45-746181a798b2">

Please note
- overall size
- font size
- (dis)proportion of line width between font and border 
- touch area has disappeared

2023-10-27 11:43 UTC, eronisko commented on app.vue
> +                        <span>{{ micrio.currentStepIndex + 1 }}.</span> <span>{{ micrio.markerRef.title }}</span>
<img width="667" alt="image" src="https://github.com/SlovakNationalGallery/sakra-stex/assets/1374745/42f8e616-d31a-4620-a1da-cea43c2f6e09">
numbers seem off (4 vs 5)

2023-10-27 14:10 UTC, FrantisekMichalSebestyen commented on components/Micrio.vue
> +  const tour = micrioRef.value?.state
The problem I have is that when i try to access tour in computed or pass it as a prop. The app starts rerendering like crazy. Dunno why yet. Thats is why i set it in computed variable

2023-12-21 09:47 UTC, closed without merging

2023-12-21 09:47 UTC, eronisko commented
#2