Re-design #2
SlovakNationalGallery/sakra-stex pull request #2
Opened 2023-12-01 09:22 UTC by eronisko

2023-12-06 09:43 UTC, FrantisekMichalSebestyen requested changes
Looks good, please just check this bug.
I had the same problem in my PR.
I fixed it by creating "is-marker-visible" ref in Micrio, which wasn't so nice but seemed to work

https://github.com/SlovakNationalGallery/sakra-stex/assets/28804184/6f290543-144a-4594-bd64-d69725ddf5d4

2023-12-06 09:43 UTC, FrantisekMichalSebestyen commented on app.vue
> +            :class="
Might be worth extracting to functin here

2023-12-06 11:56 UTC, FrantisekMichalSebestyen commented on components/pulsatingMarkersTimeline.ts
> +import gsap from "gsap";
Why is this in a separate file?

2023-12-21 15:47 UTC, eronisko commented
@FrantisekMichalSebestyen Could you try again please?

2024-01-12 12:40 UTC, FrantisekMichalSebestyen approved these changes
just del unused fn, then its good

2024-01-12 12:40 UTC, FrantisekMichalSebestyen commented on app.vue
> +// }
del

2024-01-25 07:55 UTC, merged